name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'  # 8:00 AM IST
    - cron: '00 14 * * *'  # 9:30 PM IST
    - cron: '00 06 * * 1-5'  # 11:30 AM IST (Mon to Fri)

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install Newman & Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run Hemanth_Inwarranty-flow_Collection.postman_collection.json \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: newman-html-reporter
          path: newman/*.html
