name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'  # 8:00 AM IST
    - cron: '00 14 * * *'  # 9:30 PM IST
    - cron: '00 06 * * 1-5'  # 11:30 AM IST (Mon to Fri)

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman & Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run Hemanth_Inwarranty-flow_Collection.postman_collection.json \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export newman/index.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-reporter
          path: newman/*.html

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API TEST Report - GITHUB ACTIONS"
          to: "hemanthvemireddy7@gmail.com"
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

            Please find the attached HTML Report generated after running the Postman tests via GitHub Actions (CI/CD Tool).

            ðŸ”— Live Report: https://hemanthvemireddy.github.io/Hemanth_Inwarranty_Flow/

            Regards,  
            Hemanth
          attachments: newman/index.html
          
